### ISSUE TITLE
CSV File introduction

### ISSUE THREAD

**Issue by XinFiner** [XinFinOrg/XDCScan#48]
Hi there
There is no way you get your XDC transaction details through CSV File, so could you please provide that option through Explorer, as it's very important for tax file purpose.
Thanks

**Comment by XinFiner** [comment]
And all Masternode holdings' reward transaction history is required for tax purpose too, and there is no way to get that details. So could you please provide that details too. Thanks

**Comment by AnilChinchawale** [comment]
The team is working on providing a solution to the above query.

**Comment by XinFiner** [comment]
Very good steps sir!!!
Thank you for your work.

**Comment by AnilChinchawale** [comment]
Hello @XinFiner,

Kindly note that on a newer version of explorer you can download transaction and reward history in CSV format, Kindly use the below explorers.

Block Explorer1 : (https://explorer.xinfin.network/)
Block Explorer2 : (https://xdc.network/)
Block Explorer3 : (https://xdc.blocksscan.io/)
Block Explorer4 : (https://observer.xdc.org/)
