### ISSUE TITLE
It run failed!

### ISSUE THREAD

**Issue by wodingdong** [XinFinOrg/XDCScan#74]
npm run dev :

> # npm run dev

> > XinFinScan@3.0.0 dev /var/node/xdc/XDCScan
> > concurrently "nodemon tools/sync.js " "nodemon app.js"
> 
> [0] [nodemon] 1.19.4
> [1] [nodemon] 1.19.4
> [1] [nodemon] to restart at any time, enter `rs`
> [1] [nodemon] watching dir(s): *.*
> [1] [nodemon] watching extensions: js,mjs,json
> [1] [nodemon] starting `node app.js`
> [0] [nodemon] to restart at any time, enter `rs`
> [0] [nodemon] watching dir(s): *.*
> [0] [nodemon] watching extensions: js,mjs,json
> [0] [nodemon] starting `node tools/sync.js`
> [1] config.json found.
> [0] config.json found.
> [0] Connecting ws.apothem.network:8555...
> [1] config.json found.
> [1] wss://ws.apothem.network WSURL
> [1] Connecting https://rpc.apothem.network...
> [1] Web3 connection established
> [1] config.json found.
> [1] (node:16241) Warning: Accessing non-existent property 'getLatestBlocks' of module exports inside circular dependency
> [1] (Use `node --trace-warnings ...` to show where the warning was created)
> [1] Express server listening on port 3000
> [0] Web3 Provider connected!
> [0] Checking for missing blocks
> [0] Starting Full Sync
> [0] Old block found. Starting block number = 23205760
> [0] Quiet mode enabled
> [0] Syncing chain from #23205760 -> #23205660
> [1] TypeError: Cannot read property 'XDC' of undefined
> [1]     at getQuote (/var/node/xdc/XDCScan/tools/price.js:28:37)
> [1]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> [0] Syncing chain from #23205660 -> #23205560
> [0] Patching from #23209125 to #23210401
> [0] [ - ] Lost connection to the web3 RPC or WS, reconnecting... Socket Error: undefined EPIPE
> [0] [ listenBlocks ] error: Error: CONNECTION ERROR: The connection got closed with the close code `1006` and the following reason strin                                                   g `Socket Error: undefined EPIPE`
> [0] [ syncChain ] Web3 is not connected. Retrying connection shortly...
> [0] [ runPatcher ] Web3 is not connected. Retrying connection shortly...
> [0] [ listenBlocks ] Web3 is not connected. Retrying connection shortly...
> [0] Web3 Provider connected!
> [0] Checking for missing blocks
> [0] Starting Full Sync
> [0] Old block found. Starting block number = 23205760
> [0] Quiet mode enabled
> [0] Syncing chain from #23205760 -> #23205660
> [0] Syncing chain from #23205660 -> #23205560
> [0] Patching from #23209125 to #23210404
> [0] Syncing chain from #23205560 -> #23205460
> [0] [ - ] Lost connection to the web3 RPC or WS, reconnecting... Connection dropped by remote peer.
> [0] [ listenBlocks ] error: Error: CONNECTION ERROR: The connection got closed with the close code `1006` and the following reason strin                                                   g `Connection dropped by remote peer.`
> [0] [ syncChain ] Web3 is not connected. Retrying connection shortly...
> [0] [ runPatcher ] Web3 is not connected. Retrying connection shortly...
> [0] [ listenBlocks ] Web3 is not connected. Retrying connection shortly...
> [0] Web3 Provider connected!
> [0] Checking for missing blocks
> [0] Starting Full Sync
> [0] Old block found. Starting block number = 23205741
> [0] Quiet mode enabled
> [0] Syncing chain from #23205741 -> #23205641
> [0] Syncing chain from #23205641 -> #23205541
> [0] Patching from #23209125 to #23210407
> [0] Syncing chain from #23205541 -> #23205441
> [0] [ - ] Lost connection to the web3 RPC or WS, reconnecting... Connection dropped by remote peer.
> [0] [ listenBlocks ] error: Error: CONNECTION ERROR: The connection got closed with the close code `1006` and the following reason string `Connection dropped by remote peer.`
> [0] [ syncChain ] Web3 is not connected. Retrying connection shortly...
> [0] [ runPatcher ] Web3 is not connected. Retrying connection shortly...
> [0] [ listenBlocks ] Web3 is not connected. Retrying connection shortly...
> [0] Web3 Provider connected!
> [0] Checking for missing blocks
> [0] Starting Full Sync
> [0] Old block found. Starting block number = 23205724
> [0] Quiet mode enabled
> [0] Syncing chain from #23205724 -> #23205624
> [0] Syncing chain from #23205624 -> #23205524
> [0] Syncing chain from #23205524 -> #23205424
> [0] Patching from #23209125 to #23210410
> [0] [ - ] Lost connection to the web3 RPC or WS, reconnecting... Socket Error: undefined EPIPE
> [0] [ listenBlocks ] error: Error: CONNECTION ERROR: The connection got closed with the close code `1006` and the following reason string `Socket Error: undefined EPIPE`
> [0] [ syncChain ] Web3 is not connected. Retrying connection shortly...
> [0] [ runPatcher ] Web3 is not connected. Retrying connection shortly...
> [0] [ listenBlocks ] Web3 is not connected. Retrying connection shortly...
> [0] Web3 Provider connected!
> [0] Checking for missing blocks
> [0] Starting Full Sync
> [0] Old block found. Starting block number = 23205687
> [0] Quiet mode enabled
> [0] Syncing chain from #23205687 -> #23205587
> [0] Syncing chain from #23205587 -> #23205487
> [0] Patching from #23209125 to #23210413
> [0] Syncing chain from #23205487 -> #23205387
> [0] [ - ] Lost connection to the web3 RPC or WS, reconnecting... Socket Error: undefined EPIPE
> [0] [ listenBlocks ] error: Error: CONNECTION ERROR: The connection got closed with the close code `1006` and the following reason string `Socket Error: undefined EPIPE`
> [0] [ syncChain ] Web3 is not connected. Retrying connection shortly...
> [0] [ runPatcher ] Web3 is not connected. Retrying connection shortly...
> [0] [ listenBlocks ] Web3 is not connected. Retrying connection shortly...
> [0] Web3 Provider connected!
> [0] Checking for missing blocks
> [0] Starting Full Sync
> [0] Old block found. Starting block number = 23205663
> [0] Quiet mode enabled
> [0] Syncing chain from #23205663 -> #23205563
> [0] Syncing chain from #23205563 -> #23205463
> [0] Patching from #23209125 to #23210416
> [0] Syncing chain from #23205463 -> #23205363
> [0] [ - ] Lost connection to the web3 RPC or WS, reconnecting... Connection dropped by remote peer.
> [0] [ listenBlocks ] error: Error: CONNECTION ERROR: The connection got closed with the close code `1006` and the following reason string `Connection dropped by remote peer.`
> [0] [ syncChain ] Web3 is not connected. Retrying connection shortly...
> [0] [ runPatcher ] Web3 is not connected. Retrying connection shortly...
> [0] [ listenBlocks ] Web3 is not connected. Retrying connection shortly...
> [0] Web3 Provider connected!

> # mongo --version
> MongoDB shell version v4.0.26
> git version: f12d07945bd82ff9b6726aa74b84ea4e94b06171
> OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
> allocator: tcmalloc
> modules: none
> build environment:
>     distmod: ubuntu1804
>     distarch: x86_64
>     target_arch: x86_64

**Comment by wodingdong** [comment]
> node --version
> v14.17.2

**Comment by wodingdong** [comment]
Is anyone maintain this repo?

**Comment by AnilChinchawale** [comment]
Kindly use below RPC/WS for apothem network.

RPC :- https://rpc.apothem.network
WS :- wss://ws.xinfin.network
