### ISSUE TITLE
Founfing search error and there is some time delay in explorer to saw transactions

### ISSUE THREAD

**Issue by mogithehurt** [XinFinOrg/XDCScan#76]
@blocksscanio
![image](https://user-images.githubusercontent.com/114102465/192605437-4f41cbd8-e805-4620-88ff-8dd24fe0fb9d.png)
I am getting an error message when I searched my wallet address in the search box and I am also facing some time delay in txs history.

**Comment by BlocksScanIO** [comment]
Hello @mogithehurt ,

Can you share your address and explorer link to check issue , We will check issue and provide solution on it.

**Comment by mogithehurt** [comment]
xdc91e941c0f79c2cea88f3f77d34f7d7a1ecdb2f17 
https://explorer.apothem.network/ 
Now explorer is working i have not seen any error

**Comment by BlocksScanIO** [comment]
Thank you for confirmation , I would suggest you to close this issue now.
