### ISSUE TITLE
Token transfer to Metamask wallet not recorded in Blocksscan

### ISSUE THREAD

**Issue by B3lle** [XinFinOrg/XDCScan#77]
Hi,

I am tracing this transfer from Bitrue to Metamask wallet that is not reflected in [@blocksscanio](https://www.xdc.dev/blocksscanio). Pls advise what could have been wrong with this transaction.

Thanks.

Belle

TXID: 0xebc463ce51412893c92c530e99e2871e19cc082b3fc014dc1aff51f63b162a16

Metamask Wallet Address: 0x5f56D2edE303B354C00274F72b17c10436Db096a

Metamask Screenshots
![image](https://user-images.githubusercontent.com/102605714/193633237-0868752d-9fd4-4e59-8463-91a44fcd00a4.png)

![image](https://user-images.githubusercontent.com/102605714/193633307-88a128fa-e758-440b-8096-347bea015285.png)

Bitrue Screenshot
![image](https://user-images.githubusercontent.com/102605714/193633341-36e12dd4-189e-428c-99ae-f51ed506c83b.png)

**Comment by BlocksScanIO** [comment]
Kindly check again now.

https://xdc.blocksscan.io/txs/0xebc463ce51412893c92c530e99e2871e19cc082b3fc014dc1aff51f63b162a16#overview
